export default {
  LOGIN_ACTION: "LOGIN_ACTION",
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_RESPONSE: "LOGIN_RESPONSE",
  LOGIN_ERROR: "LOGIN_ERROR",

  LOGOUT_ACTION: "LOGOUT_ACTION",
  LOGOUT_REQUEST: "LOGOUT_REQUEST"

};
