export default {

  // LOGIN_REQUEST: "LOGIN_REQUEST",
  // LOGIN_RESPONSE: "LOGIN_RESPONSE",
  // LOGIN_ERROR: "LOGIN_ERROR",

  LOGOUT_ACTION: "LOGOUT_ACTION",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",

  GET_USER_ACTION: "GET_USER_ACTION",
  LOGIN_ACTION: "LOGIN_ACTION",

  USER_REQUEST: "GET_USER_REQUEST",
  USER_RESPONSE: "GET_USER_RESPONSE",
  USER_ERROR: "GET_USER_ERROR"

  //
  // GET_USER_REQUEST: "GET_USER_REQUEST",
  // GET_USER_RESPONSE: "GET_USER_RESPONSE",
  // GET_USER_ERROR: "GET_USER_ERROR"
};
