export default {

  // LOGIN_REQUEST: "LOGIN_REQUEST",
  // LOGIN_RESPONSE: "LOGIN_RESPONSE",
  // LOGIN_ERROR: "LOGIN_ERROR",

  LOGOUT_ACTION: "LOGOUT_ACTION",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",

  GET_USER_ACTION: "GET_USER_ACTION",
  LOGIN_ACTION: "LOGIN_ACTION",

  USER_REQUEST: "GET_USER_REQUEST",
  USER_RESPONSE: "GET_USER_RESPONSE",
  USER_ERROR: "GET_USER_ERROR",

  GET_ALL_USERS_ADMIN_ACTION: "GET_ALL_USERS_ADMIN_ACTION",

  GET_ALL_USERS_ADMIN_REQUEST: "GET_ALL_USERS_ADMIN_REQUEST",
  GET_ALL_USERS_ADMIN_RESPONSE: "GET_ALL_USERS_ADMIN_RESPONSE",
  GET_ALL_USERS_ADMIN_ERROR: "GET_ALL_USERS_ADMIN_ERROR",

  SELECT_USER_IN_LIST_ACTION: "SELECT_USER_IN_LIST",
  SELECT_USER_IN_LIST_REQUEST: "SELECT_USER_IN_LIST_REQUEST",
  SELECT_USER_IN_LIST_RESPONSE: "SELECT_USER_IN_LIST_RESPONSE",
  SELECT_USER_IN_LIST_ERROR: "SELECT_USER_IN_LIST_ERROR",

  BANNED_USER_ACTION: "BANNED_USER_ACTION",

  SIGN_UP_ACTION: "SIGN_UP_ACTION",

  DROP_DOWN_CLICK: "DROP_DOWN_CLICK",
  OUT_CLICK: 'OUT_CLICK',

  SELECT_CONTEST_TYPE: 'SELECT_CONTEST_TYPE',
};
